DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS release_files;
DROP TABLE IF EXISTS releases;
DROP TABLE IF EXISTS binaries;
DROP TABLE IF EXISTS parts;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS categories;
